"""Initial migration

Revision ID: 009340ecbb8e
Revises: 
Create Date: 2024-09-18 11:33:03.203960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009340ecbb8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification')

    # ### end Alembic commands ###
